name: Frank Sauce
favicon: null
layout_spectrum: 0.15564353950321674
typography_spectrum: 0.2901402567513287
title: Frank Sauce
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.5
  lightness: 0.5731769604608417
  saturation: 0.20796587062068284
  rhythmicContrast: 0.5
purpose: []
